#port 지정 => default 8080
#spring seetting => DB (datasource) , JPA , ThymeLeaf , Mybatis , Logginh , security , springAI , websocket = 카프카
spring: 
  datasource:
    url: jdbc:oracle:thin:@192.168.0.26:1521:XE
    username: hr
    password: happy
    driver-class-name: oracle.jdbc.driver.OracleDriver

#파일 업로드


# JAP -> Hibernate -> SQL문장 생성 -> Oracle DB 실행
# SELECT NVL(Max(no)+1,1) FROM board   => Oracle
# SELECT IFNULL(Max(no)+1,1) FROM board  => Mysql
  jpa:
    database: oracle
    properties:
      hibernate: 
        # 각 데이터베이스에 맞는 SQL문법 생성
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        user_sql_comments: true
   
  thymeleaf: 
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML

mybatis: 
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml
  
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

